### ISSUE TITLE
Question about how to use Chula RBC-12-Dataset on YOLOV5

### ISSUE THREAD

**Issue by HongyanL** [martinschatz-cz/SciCount#1]
Hey, I attended the seminar you hosted, and I found using deep learning to detect cells is quite interesting. However, when I was trying to reproduce the work you did on Chula RBC-12-Dataset, I found the labels on this image are just points, which can't be used for training, so I'm just wondering how did you get the result you showed in this folder? [SmearCounting](https://github.com/martinschatz-cz/SciCount/tree/main/SmearCounting) 
Thank you so much!

**Comment by martinschatz-cz** [comment]
Hi @HongyanL, 
sorry for the late reply, I was on my holiday. I am uploading example notebooks with augmentation today. LTEE two class detection and classification is already uploaded. And I will continue with the example of the SmearCounting. You will find it under example_notebooks folder.

**Comment by HongyanL** [comment]
Thank you so much and really appreciate that!

**Comment by martinschatz-cz** [comment]
You are welocme!
